#!/bin/bash

BASE=$(echo $0|sed 's/[^/]*$//')
[ "$BASE" == "" ] && BASE='.'

cd $BASE

# TODO: Handle this better
if [ -e "../../deployment.cfg" ] ; then
  P=$(pwd) 
  export KB_DEPLOYMENT_CONFIG=$P/../../deployment.cfg
fi

# Keep the configs for things in the django.conf file
source ./django.conf

PIDFILE=$ABSBASE/var/service.pid

if [ -e $PIDFILE ]; then
   PID=$(cat $PIDFILE)
   TMP=$(ps -p $PID | grep $PID)
   # If it showed up in the PS output, then it is already up
   if [ $? = "0" ]; then
    echo "Service already running"
    exit # Exit
   fi
fi

python authorization_server/manage.py runfcgi host=$FCGI_IP port=$FCGI_PORT pidfile=$PIDFILE workdir=$(pwd) outlog=$ABSBASE/var/server.out errlog=$ABSBASE/var/server.err

