#!/bin/bash

BASE=$(echo $0|sed 's/[^/]*$//')
[ "$BASE" == "" ] && BASE='.'

cd $BASE

# Keep the configs for things in the django.conf file
source ./django.conf

PIDFILE=$ABSBASE/var/service.pid

if [ -e $PIDFILE ]; then
   PID=$(cat $PIDFILE)
   ps -p $PID | grep $PID
   # If it showed up in the PS output, then it is already up
   if [ $? = "0" ]; then
    echo "Service already running"
    exit # Exit
   fi
fi

python authorization_server/manage.py runfcgi host=$FCGI_IP port=$FCGI_PORT pidfile=$pidfile workdir=$(pwd) outlog=$ABSBASE/var/server.out errlog=$ABSBASE/var/server.err

